'use strict';
module.exports = {

    countries: [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua & Deps",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central African Rep",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo { Democratic Rep }",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea - Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland { Republic }",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea North",
        "Korea South",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar, { Burma }",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "St Kitts & Nevis",
        "St Lucia",
        "Saint Vincent & the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome & Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad & Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ],
    citiesUAE: ['Abu dahbi', 'Dubai', 'Sharjah', 'Al ain', 'Ajman', 'Ras al Khaimah', 'Fujairah', 'Umm Al quwain'],
    dubaiAreas: ['Abu Hail', 'Al Awir First', 'Al Awir Second', 'Aleyas', "Al Bada'a", 'Al Baraha', 'Al Barsha First', 'Al Barsha Second',
        'Al Barsha Third', 'Al Barsha South First', 'Al Barsha South Second', '	Al Barsha South Third', 'Al Barsha South Fourth', 'Al Barsha South Fifth'
        , 'Al Buteen', 'Al Corniche', 'Al Dhagaya', 'Al Faqa', 'Al Garhoud', 'Al Hamriya, Dubai', 'Al Hamriya Port', 'Al Hathmah', 'Al Hebiah First',
        'Al Hebiah Fourth', 'Al Hebiah Fifth', 'Al Hebiah Second', 'Al Hebiah Sixth', 'Al Hebiah Third', 'Al Hudaiba', 'Al Jaddaf', 'Al Jafiliya', 'Al Karama',
        'Al Khabisi', 'Al Khawaneej First', 'Al Khawaneej Second', 'Al Kheeran', 'Al Khairan First', 'Al Kifaf', 'Al Layan 1', 'Al Layan 2', 'Al Lisaili', 'Al Maha',
        'Al Mamzar', 'Al Manara', 'Al Mankhool', 'Al Merkad', 'Al Marmoom', 'Al Meryal', 'Al Mizhar First', 'Al Mizhar Second', 'Al Mizhar Third',
        'Al Muraqqabat',
        'Al Murar',
        'Al Muteena',
        'Al Nahda First',
        'Al Nahda Second',
        "Al O'shoosh",
        'Al Quoz First',
        'Al Quoz Industrial First',
        'Al Quoz Industrial Fourth',
        'Al Quoz Industrial Second',
        'Al Quoz Industrial Third',
        'Al Quoz Second',
        'Al Quoz Third',
        'Al Quoz Fourth',
        'Al Qusais First',
        'Al Qusais Industrial First',
        'Al Qusais Industrial Second',
        'Al Qusais Industrial Third',
        'Al Qusais Industrial Fourth',
        'Al Qusais Industrial Fifth',
        'Al Qusais Second',
        'Al Raffa',
        'Al Ras',
        'Al Rashidiya',
        'Al Rigga',
        'Al Rowaiyah First',
        'Al Rowaiyah Second',
        'Al Rowaiyah Third',
        'Al Sabkha',
        'Al Safa First',
        'Al Safa Second',
        'Al Safouh First',
        'Al Safouh Second',
        'Al Satwa',
        'Al Selal',
        'Al Shindagha',
        'Al Souk Al Kabir',
        'Al Thanyah First',
        'Al Thanyah Second',
        'Al Thanyah Third',
        'Al Thanyah Fourth',
        'Al Thanyah Fifth',
        'Al Ttay',
        'Al Twar First',
        'Al Twar Second',
        'Al Twar Third',
        'Al Twar Fourth',
        'Al Wajeha Al Bahriah',
        "Al Warqa'a Fifth",
        "Al Warqa'a First",
        "Al Warqa'a Fourth",
        "Al Warqa'a Second",
        "Al Warqa'a Third",
        'Al Wasl',
        'Al Wohoosh',
        'Al Waheda',
        'Al Yalayis 1',
        'Al Yalayis 2',
        'Al Yalayis 3',
        'Al Yalayis 4',
        'Al Yalayis 5',
        'Al Yufrah 1',
        'Al Yufrah 2',
        'Ayal Nasir',
        'Business Bay',
        'Bu Kadra',
        'Downtown Dubai',
        'Corniche Deira',
        'Dubai International Airport',
        'Dubai Investment Park First',
        'Dubai Investment Park Second',
        'Enkhali',
        'Ghadeer Barashy',
        'Grayteesah',
        'Hadaeq Sheikh Mohammed Bin Rashid',
        'Hatta',
        'Hefair',
        'Hessyan First',
        'Hessyan Second',
        'Hor Al Anz',
        'Hor Al Anz East',
        'Jabal Ali First',
        'Jabal Ali Second',
        'Jabal Ali Third',
        'Jebel Ali Industrial First',
        'Jabal Ali Industrial Second',
        'Jabal Ali Industrial Third',
        'Jumeira First',
        'Jumeira Second',
        'Jumeira Third',
        'Jumeirah Bay',
        'Jumeirah Island 2',
        'Le Hemaira',
        'Lehbab First',
        'Lehbab Second',
        'Madinat Al Mataar',
        'Madinat Dubai Al Melaheyah',
        'Madinat Hind 1',
        'Madinat Hind 2',
        'Madinat Hind 3',
        'Madinat Hind 4',
        'Margab',
        'Margham',
        'Marsa Dubai',
        "Me'aisem First",
        "Me'aisem Second",
        'Mena Jabal Ali',
        'Mereiyeel',
        'Mirdif',
        'Mugatrah',
        'Muhaisnah Fourth',
        'Muhaisnah Second',
        'Muhaisnah Third',
        'Muhaisnah First',
        'Muhaisnah Fifth',
        'Mushraif',
        'Nad Al Hammar',
        'Nadd Al Shiba First',
        'Nadd Al Shiba Fourth',
        'Nadd Al Shiba Second',
        'Nadd Al Shiba Third',
        'Nadd Hessa',
        'Nad Shamma',
        'Naif',
        'Nazwah',
        'Oud Al Muteena First',
        'Oud Al Muteena Second',
        'Oud Metha',
        'Nakhlat Deira',
        'Jebel Ali Palm',
        'Palm Jumeirah',
        'Port Saeed',
        'Ras Al Khor',
        'Ras Al Khor Industrial First',
        'Ras Al Khor Industrial Second',
        'Ras Al Khor Industrial Third',
        'Remah',
        'Rigga Al Buteen',
        'Saih Al Dahal',
        'Saih Al Salam',
        "Saih Shua'alah",
        'Saih Shuaib 1',
        'Saih Shuaib 2',
        'Saih Shuaib 3',
        'Saih Shuaib 4',
        'Trade Centre 1',
        'Trade Centre 2',
        'Umm Al Daman',
        "Umm Al Mo'meneen",
        'Umm Al Sheif',
        'Umm Eselay',
        'Umm Hurair First',
        'Umm Hurair Second',
        'Umm Ramool',
        'Umm Suqeim First',
        'Umm Suqeim Second',
        'Umm Suqeim Third',
        'Wadi Alamardi',
        'Wadi Al Safa 2',
        'Wadi Al Safa 3',
        'Wadi Al Safa 4',
        'Wadi Al Safa 5',
        'Wadi Al Safa 6',
        'Wadi Al Safa 7',
        'Wadi Alshabak',
        'Warsan First',
        'Warsan Second',
        'Warsan Third',
        'Warsan Fourth',
        'World Islands',
        'Yaraah',
        "Za'abeel First",
        "Za'abeel Second"
    ],
}